name: Linux Container Node Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: acryudai.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t acryudai.azurecr.io/web-app-for-containers-yudai:${{ github.sha }}
          docker push acryudai.azurecr.io/web-app-for-containers-yudai:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "web-app-for-containers-yudai"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "acryudai.azurecr.io/web-app-for-containers-yudai:${{ github.sha }}"
